name:                rescheme
version:             0.1.0.0
github:              "1ntEgr8/rescheme"
license:             BSD3
author:              "Elton Pinto"
maintainer:          "example@example.com"
copyright:           "2021 Elton Pinto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rescheme#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- parsec

library:
  source-dirs: src

executables:
  rescheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rescheme

tests:
  rescheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rescheme
    - hspec
